# Generated by Django 4.1.5 on 2023-01-18 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_post_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default='placeholder.jpg', null=True, upload_to='images'),
        ),
    ]
